/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import clases.Administrador;
import clases.Bolilla;
import controladores.ControllerAdmin;
import clases.Juego;
import java.util.ArrayList;

/**
 *
 * @author gmedina
 */
public class Ui_Admin extends javax.swing.JDialog {
    private Administrador admin;
    private ControllerAdmin ca;
    /**
     * Creates new form NewJDialog
     */
    public Ui_Admin(java.awt.Frame parent, boolean modal, Administrador admin) {
        super(parent, modal);
        initComponents();
        this.admin = admin;
        this.ca = new ControllerAdmin(this, admin);
        this.iniciar();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeJuegos = new javax.swing.JList();
        jugadorQueAnoto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDeJugadores = new javax.swing.JList();
        cantBolillasSorteadas = new javax.swing.JLabel();
        numeroJuegoValue = new javax.swing.JLabel();
        estadoJuegoValue = new javax.swing.JLabel();
        ganadorJuegoValue = new javax.swing.JLabel();
        cantBolillasSorteadasValue = new javax.swing.JLabel();
        numeroJuego = new javax.swing.JLabel();
        estadoJuego = new javax.swing.JLabel();
        ganadorJuego = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaDeBolillas = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listaDeJuegos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDeJuegos.setFocusable(false);
        listaDeJuegos.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        listaDeJuegos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDeJuegosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listaDeJuegos);

        jugadorQueAnoto.setEditable(false);

        listaDeJugadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDeJugadores.setEnabled(false);
        listaDeJugadores.setFocusable(false);
        jScrollPane2.setViewportView(listaDeJugadores);

        cantBolillasSorteadas.setText("Cantidad bolillas :");

        numeroJuegoValue.setText("-");

        estadoJuegoValue.setText("-");

        ganadorJuegoValue.setText("-");

        cantBolillasSorteadasValue.setText("-");

        numeroJuego.setText("Numero de juego :");

        estadoJuego.setText("Estado :");

        ganadorJuego.setText("Ganador :");

        listaDeBolillas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listaDeBolillas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaDeBolillas.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        listaDeBolillas.setVisibleRowCount(2);
        listaDeBolillas.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaDeBolillasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(listaDeBolillas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jugadorQueAnoto)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroJuego)
                            .addComponent(estadoJuego, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ganadorJuego, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cantBolillasSorteadas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ganadorJuegoValue)
                            .addComponent(cantBolillasSorteadasValue)
                            .addComponent(estadoJuegoValue)
                            .addComponent(numeroJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroJuego)
                            .addComponent(numeroJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoJuego)
                            .addComponent(estadoJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ganadorJuego)
                            .addComponent(ganadorJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantBolillasSorteadas)
                            .addComponent(cantBolillasSorteadasValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jugadorQueAnoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDeJuegosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDeJuegosValueChanged
        ca.suscribirAJuego(listaDeJuegos.getSelectedValue());
    }//GEN-LAST:event_listaDeJuegosValueChanged

    private void listaDeBolillasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaDeBolillasValueChanged
        ca.jugadorQueAnoto(listaDeBolillas.getSelectedValue());
    }//GEN-LAST:event_listaDeBolillasValueChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantBolillasSorteadas;
    private javax.swing.JLabel cantBolillasSorteadasValue;
    private javax.swing.JLabel estadoJuego;
    private javax.swing.JLabel estadoJuegoValue;
    private javax.swing.JLabel ganadorJuego;
    private javax.swing.JLabel ganadorJuegoValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jugadorQueAnoto;
    private javax.swing.JList listaDeBolillas;
    private javax.swing.JList listaDeJuegos;
    private javax.swing.JList listaDeJugadores;
    private javax.swing.JLabel numeroJuego;
    private javax.swing.JLabel numeroJuegoValue;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.cargarJuegos();
    }
    
    public void cargarJuegos(){
        listaDeJuegos.setListData(admin.getBingo().getJuegos().toArray());
    }
    
    public void cargarJugadores(Juego juego){
        listaDeJugadores.setListData(juego.getJugadores().toArray());        
    }
    
    public void cargarNumero(Juego juego){
        numeroJuegoValue.setText(juego.getNumero()+"");    
    }
    
    public void cargarEstadoCantidadBolillasYBolillero(Juego juego, int cantBolillasSorteadas, ArrayList<Bolilla> bolillas){
        estadoJuegoValue.setText(juego.getEstado().toString());
        cantBolillasSorteadasValue.setText(cantBolillasSorteadas+"");
        listaDeBolillas.setListData(bolillas.toArray());
    }
    
    public void cargarGanador(Juego juego){
        ganadorJuegoValue.setText(juego.getGanador() == null ? "-" : juego.getGanador().getNombre());        
    }      
    
    public void cargarJugadorQueAnoto(String nombre){
        jugadorQueAnoto.setText(nombre);
    }
}
