/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import clases.Administrador;
import controladores.ControllerAdmin;

/**
 *
 * @author gmedina
 */
public class Ui_Admin extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    Administrador a;
    ControllerAdmin ca;
    
    public Ui_Admin(java.awt.Frame parent, boolean modal, Administrador a) {
        super(parent, modal);
        initComponents();
        this.a = a;
        //this.ca = new ControllerAdmin(this, a);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeJuegos = new javax.swing.JList();
        jugadorQueAnoto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaDeBolillas = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaDeJugadores = new javax.swing.JList();
        cantBolillasSorteadas = new javax.swing.JLabel();
        numeroJuegoValue = new javax.swing.JLabel();
        estadoJuegoValue = new javax.swing.JLabel();
        ganadorJuegoValue = new javax.swing.JLabel();
        cantBolillasSorteadasValue = new javax.swing.JLabel();
        numeroJuego = new javax.swing.JLabel();
        estadoJuego = new javax.swing.JLabel();
        ganadorJuego = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listaDeJuegos.setEnabled(false);
        listaDeJuegos.setFocusable(false);
        listaDeJuegos.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane1.setViewportView(listaDeJuegos);

        jugadorQueAnoto.setEditable(false);
        jugadorQueAnoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugadorQueAnotoActionPerformed(evt);
            }
        });

        listaDeBolillas.setEnabled(false);
        listaDeBolillas.setFocusable(false);
        listaDeBolillas.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane3.setViewportView(listaDeBolillas);

        listaDeJugadores.setEnabled(false);
        listaDeJugadores.setFocusable(false);
        jScrollPane2.setViewportView(listaDeJugadores);

        cantBolillasSorteadas.setText("Cantidad bolillas :");

        numeroJuegoValue.setText("-");

        estadoJuegoValue.setText("-");

        ganadorJuegoValue.setText("-");

        cantBolillasSorteadasValue.setText("-");

        numeroJuego.setText("Numero de juego :");

        estadoJuego.setText("Estado :");

        ganadorJuego.setText("Ganador :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jugadorQueAnoto)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numeroJuego)
                            .addComponent(estadoJuego, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ganadorJuego, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cantBolillasSorteadas, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ganadorJuegoValue)
                            .addComponent(cantBolillasSorteadasValue)
                            .addComponent(estadoJuegoValue)
                            .addComponent(numeroJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numeroJuego)
                            .addComponent(numeroJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(estadoJuego)
                            .addComponent(estadoJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ganadorJuego)
                            .addComponent(ganadorJuegoValue))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cantBolillasSorteadas)
                            .addComponent(cantBolillasSorteadasValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jugadorQueAnoto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugadorQueAnotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugadorQueAnotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugadorQueAnotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
                Ui_Admin dialog = new Ui_Admin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cantBolillasSorteadas;
    private javax.swing.JLabel cantBolillasSorteadasValue;
    private javax.swing.JLabel estadoJuego;
    private javax.swing.JLabel estadoJuegoValue;
    private javax.swing.JLabel ganadorJuego;
    private javax.swing.JLabel ganadorJuegoValue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jugadorQueAnoto;
    private javax.swing.JList listaDeBolillas;
    private javax.swing.JList listaDeJuegos;
    private javax.swing.JList listaDeJugadores;
    private javax.swing.JLabel numeroJuego;
    private javax.swing.JLabel numeroJuegoValue;
    // End of variables declaration//GEN-END:variables
}
