/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import clases.Jugador;
import componenteGrid.ListaPaneles;
import controladores.ControllerJugador;
/**
 *
 * @author Ezko
 */
public class Ui_Jugador extends javax.swing.JDialog {
    private Jugador j;
    private ControllerJugador cj;
    
    public Ui_Jugador(java.awt.Frame parent, boolean modal, Jugador j) {
        super(parent, modal);
        initComponents();
        this.j = j;
        cj =  new ControllerJugador(this, j);
        this.generarCarton();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        header = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        saldoJugador = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        numeroSorteado = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        montoPozo = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        estadoDelJuego = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        listaJugadores = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        figurasHabilitadas = new javax.swing.JList();
        continuar = new javax.swing.JButton();
        abandonar = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        numerosSorteados = new javax.swing.JList<>();
        cartones = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        header.setEditable(false);
        header.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        saldoJugador.setEditable(false);
        saldoJugador.setToolTipText("");
        jScrollPane1.setViewportView(saldoJugador);

        numeroSorteado.setEditable(false);
        jScrollPane2.setViewportView(numeroSorteado);

        montoPozo.setEditable(false);
        jScrollPane3.setViewportView(montoPozo);

        estadoDelJuego.setEditable(false);
        jScrollPane4.setViewportView(estadoDelJuego);

        listaJugadores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listaJugadores.setEnabled(false);
        listaJugadores.setFocusable(false);
        jScrollPane5.setViewportView(listaJugadores);

        jScrollPane6.setToolTipText("");
        jScrollPane6.setEnabled(false);
        jScrollPane6.setFocusable(false);

        figurasHabilitadas.setToolTipText("");
        jScrollPane6.setViewportView(figurasHabilitadas);

        continuar.setText("Continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });

        abandonar.setText("Abandonar");

        numerosSorteados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        numerosSorteados.setEnabled(false);
        numerosSorteados.setFocusable(false);
        numerosSorteados.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        jScrollPane7.setViewportView(numerosSorteados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cartones)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(abandonar, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(continuar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(continuar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(abandonar))
                    .addComponent(cartones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        this.continuar();
    }//GEN-LAST:event_continuarActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abandonar;
    private javax.swing.JScrollPane cartones;
    private javax.swing.JButton continuar;
    private javax.swing.JTextPane estadoDelJuego;
    private javax.swing.JList figurasHabilitadas;
    private javax.swing.JTextField header;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JList listaJugadores;
    private javax.swing.JTextPane montoPozo;
    private javax.swing.JTextPane numeroSorteado;
    private javax.swing.JList<String> numerosSorteados;
    private javax.swing.JTextPane saldoJugador;
    // End of variables declaration//GEN-END:variables
    
    public void generarCarton(){
       ListaPaneles listaPaneles = new ListaPaneles(j.getJuego().getFilas(),j.getJuego().getColumnas());
       cj.generarCarton(listaPaneles);
       cartones.setViewportView(listaPaneles);
       this.actualizarInterfaz();
    }
    
    public void actualizarInterfaz(){
        saldoJugador.setText("$"+j.getSaldo());
        listaJugadores.setListData(j.getJuego().getJugadores().toArray());
        figurasHabilitadas.setListData(j.getJuego().getFigurasHabilitadas().toArray());
        header.setText(j.getNombre() + " COMPLETAR NUMERO DE JUEGO");
        estadoDelJuego.setText("HACER ESTADO");
        montoPozo.setText("HACER EL POZO");
        numeroSorteado.setText("Hacer NUMERO SORTEADO");
//        numerosSorteados.setListData(); ESTO HAY QUE HACERLO TMB
        
    }

    private void continuar() {
        j.setEstado(Jugador.EstadoJugador.Continuar);
        j.getJuego().continuar();
    }
}
